# Example Cloud Build Configuration File
#
# define the build steps
steps:
  # install the app dependencies
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]

  # execute the tests
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "test"]

  # build an artifact using the docker builder
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--build-arg",
        "NODE_ENV=production",
        "-t",
        "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA",
        ".",
      ]

  # push the artifact to a GCR repository
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA"]

  # deploy the app to a GKE cluster using the `gke-deploy` builder
  # https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/gke-deploy
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --image=gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA
      - --location=${_GKE_CLUSTER_LOCATION}
      - --cluster=${_GKE_CLUSTER_NAME}

substitutions:
  _GKE_CLUSTER_LOCATION: europe-west3 # must be substituted
  _GKE_CLUSTER_NAME: private-cluster # must be substituted
